dappx/urls.py
# dappx/urls.py
from django.conf.urls import url
from dappx import views
from django.contrib import admin
from django.urls import path
from django.urls import include
# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),

	#path('',views.head),
	path('user_login/delhi.html',views.delhi),
	path('user_login/about.html',views.about),
	path('user_login/destination.html',views.dest),
	path('user_login/agra.html',views.agra),
	path('user_login/delhi.html',views.delhi),
	path('user_login/h_page.html',views.head),
	path('user_login/header.html',views.header),
	path('user_login/jaipur.html',views.jaipur),
	path('user_login/hpme.html',views.home),
	path('user_login/kerala.html',views.kerala),
	path('user_login/kolkata.html',views.kolkata),
	path('user_login/map_page.html',views.map),
	path('user_login/varanasi.html',views.varanasi),
	path('user_login/login.html',views.user_logout),
	
	
	
	
]

dprojx/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views
urlpatterns = [
	path('admin/', admin.site.urls),
	path('accounts/login/',views.user_login),
	#path('dappx/',views.user_login),
	url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),

]

dappx/models.py
# dappx/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	portfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	def __str__(self):
  		return self.user.username

dappx/forms.py
# dappx/forms.py
from django import forms
from dappx.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

dappx/views.py
# Create your views here.
# dappx/views.py
from django.shortcuts import render
from dappx.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
def index(request):
    return render(request,'dappx/index.html')
    
def head(request):
	return render(request,'dappx/h_page.html')
	
def about(request):
	return(render(request,"dappx/about.html"))	
	
def dest(request):
	return(render(request,"dappx/destination.html"))

def agra(request):
	return(render(request,"dappx/agra.html"))
	
def delhi(request):
	return(render(request,"dappx/delhi.html"))

def header(request):
	return(render(request,"dappx/header.html"))
	
def jaipur(request):
	return(render(request,"dappx/jaipur.html"))
	
def home(request):
	return(render(request,"dappx/home.html"))

def kerala(request):
	return(render(request,"dappx/kerala.html"))
	
def kolkata(request):
	return(render(request,"dappx/kolkata.html"))

def map(request):
	return(render(request,"dappx/map_page.html"))

def varanasi(request):
	return(render(request,"dappx/varanasi.html"))

@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    #return HttpResponseRedirect(reverse('head'))
    return render(request, 'dappx/login.html', {})
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'dappx/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                #return HttpResponseRedirect('/dappx/'))
                return render(request,'dappx/h_page.html',{})
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})
        

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

templates/dappx/about.html
{% load static %}
<html>
<head>
	<title>about</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/mylink.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">	
	<style type="text/css">
			body 
			{
				background-opacity: 0.1;
		        background-position: center;
	    		background-repeat: no-repeat;
	    		background-size: 100%;
	    		background-attachment: fixed;
	    		margin: 0px;
			}
			.nav-tab:hover {
				background-color: #f79859;
			}
			.nav-tab {
				padding: 10px;
				color: black;
				border-left: 0.2px solid grey;
				border-radius: 4px;
			}
			.nav-tab a:link {
				color: black;
			}
			.nav-tab a:hover, a:active, a:focus {
				color: black;
			}
			#header {
				border: 0.2px solid grey;
			}
			.dropdown {
				position: absolute;
				margin-top: 1%;
				margin-left: -1%;
				background-color: rgba(245, 255, 250,0.6);
				opacity: 0;
				-webkit-transition: opacity 1s ease-in;
				-moz-transition: opacity 1s ease-in;
		    	-o-transition: opacity 1s ease-in;
    			-ms-transition: opacity 1s ease-in;
    			transition: opacity 1s ease-in;
			}
			.dropdown td {
				border-bottom: 0.2px solid grey;
				padding-top: 10px;
				padding-bottom: 10px;
				width: 160px;
				padding: 10px;
				cursor: pointer;
			}
			.destinations:hover .dropdown {
				opacity: 1;
			}
	</style>
	<script>
		function openNav() {
  			document.getElementById("myNav").style.width = "100%";
		}

		function closeNav() {
  			document.getElementById("myNav").style.width = "0%";
		}
		</script>
</head>
	<body>
		<a href="map_page.html">
			<i class="fa fa-globe fa-2x" style="position: absolute;padding-top: 5px;padding-left: 20px"></i>
		</a>
		<div id="header" align="right">
			<table>
				<tr>
					<td class="nav-tab">
						<a href="h_page.html" ><i class="fa fa-home" aria-hidden="true"></i> Home</a>
					</td>
					<td class="nav-tab">
						<a href="h_page.html"><i class="fa fa-calendar-plus-o" aria-hidden="true"></i> Planner</a>						
					</td>
					<td class="nav-tab destinations">
							<a href="#"><i class="fa fa-location-arrow" aria-hidden="true"></i> Destinations</a>
								<table class="dropdown">

								<tr>
									<td>
										<a href="delhi.html" target="_blank">
											Delhi
										</a>
									</td>
								</tr>
								<tr>
									<td>
										<a href="agra.html" target="_blank">
											Agra
										</a>
									</td>
								</tr>
								<tr>
									<td>
										<a href="varanasi.html" target="_blank">
											Varanasi
										</a>
									</td>
								</tr>
								<tr>
									<td>
										<a href="jaipur.html" target="_blank">
											Jaipur
										</a>
									</td>
								</tr>
								<tr>
									<td>
										<a href="kolkata.html" target="_blank">
											Kolkata
										</a>
									</td>
								</tr>

								</table>
					</td>
					<td class="nav-tab">
						<a href="#" onclick="openNav()"><i class="fa fa-link" aria-hidden="true"></i> About</a>
					</td>
					<td class="nav-tab">
						<a href="login.html"><i  class="fa fa-user-circle-o" aria-hidden="true"></i> Log Out</a>
					</td>
					<td>
						&nbsp;
					</td>
				</tr>
			</table>
		</div>
		<div id="myNav" class="overlay">
	    	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
	    	<div class="overlay-content">
	    		<a href="#">About</a>
	    		<a href="#">Services</a>
	    		<a href="#">Clients</a>
	    		<a href="#">Contact</a>
	  		</div>
		</div>
	<div style="position: absolute; top: 7.8%; left: 0%; right: 0%; bottom: 45%; background-color: #bc721e; padding: 50px;">
			<span style="font-size: 100px;color: white; word-spacing: -40px; letter-spacing: -4px;position: absolute; left: 33%;color: #edd0ad; font-family: monospace;">
				About Us
			</span>
			<br/>
			<span style="font-size: 20px; color: white; position: absolute; left: 28%; top: 60%; font-family: monospace;">
				How we plan on changing your travel experience	
			</span>
	</div>
	<div style="position: absolute; top: 57%; text-align: center; left: 20%; right: 20%">
			<p style="font-family: Comic Sans MS; color: black; text-align: justify;">
	To make such experience easier to achieve, our focus has been how to help people travel better especially in India. For this reason, we have showcased a long list of tour packages to choose from. If you are into adventure, we probably have one for you. If you are into culture, then you have come to the right place. Our staff are routine travelers with proven track records. Should you require assistance on travel itineraries, booking, or travel advice in specific countries, please contact us and we’ll be more than happy to help you out.</p>
	<p style="font-family: Comic Sans MS; color: black; text-align: justify;">
We would like to thank those who have been very resourceful to the including our genius our visitors. At Travel India, we are looking forward to providing more value-added services to travelers around the world. We hope you enjoy surfing as much as we do.</p>
	</div>

	<script type="text/javascript">
	var slideIndex = 0;
	showSlides();

	function showSlides() {
	    var i;
	    var slides = document.getElementsByClassName("mySlides");
	    var dots = document.getElementsByClassName("dot");
	    for (i = 0; i < slides.length; i++) {
	       slides[i].style.display = "none";  
	    }
	    slideIndex++;
	    if (slideIndex > slides.length) {slideIndex = 1}    
	    for (i = 0; i < dots.length; i++) {
	        dots[i].className = dots[i].className.replace(" active", "");
	    }
	    slides[slideIndex-1].style.display = "block";  
	    dots[slideIndex-1].className += " active";
	    setTimeout(showSlides, 2000); // Change image every 2 seconds
	}

	</script>
</body>
</html>

templates/dappx/agra.html
{% load static %}
<html>
<head>
	<title>agra</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/mylink1.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">	
	<style type="text/css">
			body 
			{	
				background-image: url(agrabg2.jpg);
		    	/* Center and scale the image*/
		        background-position: center;
	    		background-repeat: no-repeat;
	    		background-size: 100%;
	    		background-attachment: fixed;
	    		margin: 0px;
			}
	</style>

</head>
	<body>
		<a href="map_page.html"><i class="material-icons" style="font-size:50px;position: absolute;left: 25px; top: 8px">public &emsp; &emsp;</i></a>
		<div id="header" align="right">
		<a href="h_page.html" style="color: #e15b00; border-bottom: 2px solid #e15b00">&emsp;&emsp; Home <i class="fa fa-angle-down" style="font-size:15px"></i>&emsp; &emsp;</a>
		
		<a href="h_page.html"> Go Back <i class="fa fa-angle-down" style="font-size:15px"></i>&emsp; &emsp;</a>
		<div id="myNav" class="overlay">
	    	<a href="javascript:void(0)" class="closebtn"	 onclick="closeNav()">&times;</a>
	    	<div class="overlay-content">
	    		<a href="#">About</a>
	    		<a href="#">Services</a>
	    		<a href="#">Clients</a>
	    		<a href="#">Contact</a>
	  		</div>
		</div>
		
		
		<script>
			function openNav() {
	  		document.getElementById("myNav").style.width = "100%";
			}

			function closeNav() {
	  		document.getElementById("myNav").style.width = "0%";
			}
		</script>




	<table>
	<tr>
	<td>
	<div class="slideshow-container">
		<div class="mySlides fade">
		  
		  <img src="{% static 'css/tajmahal.jpg' %}" style="width:650px;height:452px">
		  <div style="color: beige;
	  				font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Taj Mahal</div>
		</div>

		<div class="mySlides fade">
		  
		  <img src="{% static 'css/agrafort.jpg' %}" style="width:650px;height:452px">
		  <div style="color: yellow;
					font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Agra Fort</div>
		</div>
		<div class="mySlides fade">
		  
		  <img src="{% static 'css/fatehpursikri.jpg' %}" style="width:650px;height:452px">
		  <div style="color: white;
	  				font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Fatehpur Sikri</div>
		</div>

		<div class="mySlides fade">
		  
		  <img src="{% static 'css/agramarket2.jpg' %}" style="width:650px;height:452px">
		  <div style="color: white;
	  				font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Markets of Agra</div>
		</div>
		<div style="text-align:center">
		  <span class="dot"></span> 
		  <span class="dot"></span> 
		  <span class="dot"></span>
		  <span class="dot"></span> 
		</div>
	</div>	
	</td>
	<td style="display:inline"><p style="font-family: Comic Sans MS; color: black; font-size: 30px; text-shadow: white 2px 1px"> AGRA</p><p style="font-family: Comic Sans MS">Wish to realize a dream vacation? Welcome to the amazing tourism city of the Taj Mahal - Agra, India.</p><p style="font-family: Comic Sans MS">The seat of the great Mughal rulers for ages, Agra offers its treasure trove for all the tourists from India and abroad.</p><p style="font-family: Comic Sans MS">The city stands in testimony to the great amount of architectural activity of the Mughals.</p><p style="font-family: Comic Sans MS"> Taj Mahal is the epitome of love, poem in white marble,one of the Seven Wonders of the World besides being the pride of India.</p><p style="font-family: Comic Sans MS">Agra is also known for its flourishing bazars (markets) where the true cosmopolitan character of the city comes out in all its dimensions.</p><p style="font-family: Comic Sans MS"> With Taj Mahal, Fatehpur Sikri and Agra Fort already in the list of to do things in Agra, the charms of Agra bazar is something unique, which cannot be missed.</p>
	</td>
	</tr>
	</table>
	<br>
	<script type="text/javascript">
	var slideIndex = 0;
	showSlides();

	function showSlides() {
	    var i;
	    var slides = document.getElementsByClassName("mySlides");
	    var dots = document.getElementsByClassName("dot");
	    for (i = 0; i < slides.length; i++) {
	       slides[i].style.display = "none";  
	    }
	    slideIndex++;
	    if (slideIndex > slides.length) {slideIndex = 1}    
	    for (i = 0; i < dots.length; i++) {
	        dots[i].className = dots[i].className.replace(" active", "");
	    }
	    slides[slideIndex-1].style.display = "block";  
	    dots[slideIndex-1].className += " active";
	    setTimeout(showSlides, 2000); // Change image every 2 seconds
	}

	</script>

	    
	</body>
</html>

templates/dappx/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'dappx:register' %}">Sign Up</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/dappx/delhi.html
{% load static %}
<html>
<head>
	<title>delhi</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/mylink1.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">	
	<style type="text/css">
			body 
			{	
				background-image: url(delhibg2.jpg);
		    	/* Center and scale the image*/
		    	background-opacity: 0.1; 
		        background-position: center;
	    		background-repeat: no-repeat;
	    		background-size: 100%;
	    		background-attachment: fixed;
	    		margin: 0px;
			}
	</style>

</head>
	<body>
		<a href="map_page.html"><i class="material-icons" style="font-size:50px;position: absolute;left: 25px; top: 8px">public &emsp; &emsp;</i></a>
		<div id="header" align="right">
		<a href="h_page.html" style="color: #e15b00; border-bottom: 2px solid #e15b00">&emsp;&emsp; Home <i class="fa fa-angle-down" style="font-size:15px"></i>&emsp; &emsp;</a>
		
		<a href="h_page.html"> Go Back <i class="fa fa-angle-down" style="font-size:15px"></i>&emsp; &emsp;</a>
		<div id="myNav" class="overlay">
	    	<a href="javascript:void(0)" class="closebtn"	 onclick="closeNav()">&times;</a>
	    	<div class="overlay-content">
	    		<a href="#">About</a>
	    		<a href="#">Services</a>
	    		<a href="#">Clients</a>
	    		<a href="#">Contact</a>
	  		</div>
		</div>
		
		
		<script>
			function openNav() {
	  		document.getElementById("myNav").style.width = "100%";
			}

			function closeNav() {
	  		document.getElementById("myNav").style.width = "0%";
			}
		</script>


	<table>
	<tr>
	<td>
	<div class="slideshow-container">
		<div class="mySlides fade">
		  
		  <img src="{% static 'css/indiagate.jpg' %}" style="width:650px;height:452px">
		  <div style="color: white;
	  				font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">India Gate</div>
		</div>

		<div class="mySlides fade">
		  
		  <img src="{% static 'css/qutubminar.jpg' %}" style="width:650px;height:452px">
		  <div style="color: white;
					font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Qutub Minar</div>
		</div>
		<div class="mySlides fade">
		  
		  <img src="{% static 'css/RASHTRAPATI_BHAVAN.jpg' %}" style="width:650px;height:452px">
		  <div style="color: white;
	  				font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Rashtrapati Bhavan</div>
		</div>

		<div class="mySlides fade">
		  
		  <img src="{% static 'css/Lotustemple.jpg' %}" style="width:650px;height:452px">
		  <div style="color: white;
	  				font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Lotus Temple</div>
		</div>
		<div class="mySlides fade">
		  
		  <img src="{% static 'css/dillihaat.jpg' %}" style="width:650px;height:452px">
		  <div style="color: white;
	  				font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Dilli Haat</div>
		</div>
		<div class="mySlides fade">
		  
		  <img src="{% static 'css/Lotustemple.jpg' %}" style="width:650px;height:452px">
		  <div style="color: white;
	  				font-size: 20px;
	  				font-weight: 400;
	  				padding: 8px 12px;
	 	 			position: absolute;
	  				bottom: 20px;
	  				width: 100%;
	  				text-align: right;
	  				text-shadow: 2px 1px black;">Lotus Temple</div>
		</div>
		<div style="text-align:center">
		  <span class="dot"></span> 
		  <span class="dot"></span> 
		  <span class="dot"></span>
		  <span class="dot"></span> 
		</div>
	</div>	
	</td>
	<td style="display:inline">
		<p style="font-family: Comic Sans MS; color: yellow; font-size: 30px; text-shadow: black 2px 1px"> DELHI</p>
		<p style="font-family: Comic Sans MS; color: black">A symbol of the country’s rich past and thriving present, Delhi is a city where ancient and modern blend seamlessly together.</p><p style="font-family: Comic Sans MS; color: black">It is home to three World Heritage monuments—Qutub Minar, Red Fort and Humayun’s Tomb that have survived many centuries, and give an idea of architectural wonders created by emperors in the past. Central Delhi, with its tree-lined avenues, imposing structures and buildings such as the Rashtrapati Bhavan, Parliament House and India Gate, reflect Delhi’s colonial past.</p><p style="font-family: Comic Sans MS; color: black">The city stands in testimony to the great amount of architectural activity of the Mughals.</p><p style="font-family: Comic Sans MS; color: black"> Delhi has a modern, well-planned and extensive Metro network that connects all corners of Delhi; this network is still growing.</p><p style="font-family: Comic Sans MS; color:black">New additions to the city, such as Akshardham Temple and also the Lotus Temple are also great places to visit and give an idea of its multi-faceted culture.</p><p style="font-family: Comic Sans MS; color:black">For cuisine of different Indian states and an array of Indian art and craft there are three Dilli Haats.</p>
	</td>
	</tr>
	</table>
	<br>
	<script type="text/javascript">
	var slideIndex = 0;
	showSlides();

	function showSlides() {
	    var i;
	    var slides = document.getElementsByClassName("mySlides");
	    var dots = document.getElementsByClassName("dot");
	    for (i = 0; i < slides.length; i++) {
	       slides[i].style.display = "none";  
	    }
	    slideIndex++;
	    if (slideIndex > slides.length) {slideIndex = 1}    
	    for (i = 0; i < dots.length; i++) {
	        dots[i].className = dots[i].className.replace(" active", "");
	    }
	    slides[slideIndex-1].style.display = "block";  
	    dots[slideIndex-1].className += " active";
	    setTimeout(showSlides, 2000); // Change image every 2 seconds
	}

	</script>

	    
	</body>
</html>

templates/dappx/header.html
{% load static %}
<html>
<head>
	<title>something</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/mylink.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
	<div class="menu">
		<?php include 'header.php';?>
	</div>
	<h1>welcome!</h1>

</body>
</html>

templates/dappx/home.html
{%extends 'base.html'%}
{%block title%}Home{%endblock%}
{%block content%}
{% if user.is_authenticated%}
Hi  {{user.username}}!
<a href="{%url 'logout'%}">logout</a>
{%else%}
<p>you are not logged in</p>
<a href="{%url 'login'%}">login</a>
{%endif%}
{%endblock%}

templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome!</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you want a tour through Incredible India!</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}